### ISSUE TITLE
Content of the buttons 

### ISSUE THREAD

**Issue by jaspalsinghsaini** [rgerd/SwitchSpeak#1]
Will buttons (present in the 2D grid) contain an image and a small phrase printed as text? Or should we account for some other information too?

**Comment by rgerd** [comment]
We can just use dictionaries in the app as internal databases. This will help down the road as we put things into the backend. For example, each button could have a dictionary called 'optionInfo' or something:
button.optionInfo = [
    "label": "Water"
    "image": "water",
    "sound": "water.mp4",
]
We could also have other dictionaries so the image field (for example) could act like a foreign key:
images = [
    "water": iOSImageLibrary.loadImage('water.png'),
    "food": iOSImageLibrary.loadImage('food.png'),
]
These dictionaries can be defined in text files (kind of like database schemas) for easy scaling and manipulation.
